### ISSUE TITLE
Showing purple screen

### ISSUE THREAD

**Issue by Prudhvi1997** [abdullahselek/Swifty360Player#1]

**Comment by Prudhvi1997** [comment]
I am able to see purple screen, nothing else is working

**Comment by abdullahselek** [comment]
Hi @Prudhvi1997, could you please give me more details? What did you try and what is your configurations?

**Comment by Prudhvi1997** [comment]
Hi @abdullahselek, when i m running on the iPhone x device, i am getting the purple screen. please find the attached image.
![simulator screen shot - iphone x - 2018-04-13 at 18 16 07](https://user-images.githubusercontent.com/21103328/38735569-c5052046-3f46-11e8-90ff-b3d1d1f506ed.png)

**Comment by abdullahselek** [comment]
I see @Prudhvi1997 , feel free to create a pull request for the fix.

**Comment by abdullahselek** [comment]
Hi @Prudhvi1997 I did some changes, please checkout the latest changes from master and let me know if it works.

**Comment by paulius-mf** [comment]
Hi @abdullahselek, still the same

**Comment by abdullahselek** [comment]
@paulius-mf @Prudhvi1997 please check the latest master, it works now on my machine as expected. And also don't forget to let me know.

**Comment by abdullahselek** [comment]
@few28 I think your changes are not related to displaying purple screen but it seems as an improvement. Feel free to open a pull request.
