### ISSUE TITLE
Stereoscopic view

### ISSUE THREAD

**Issue by konalexiou** [abdullahselek/Swifty360Player#2]
Hi,
is there any way to use stereoscopic view when playing the video?

I used something of a hack and added two views 
with the same motionManager in a horizontal stack.
Is there a better way ?

      
        player = AVPlayer(url: fileURL)
        
        let motionManager = Swifty360MotionManager.shared
        swifty360ViewController = Swifty360ViewController(withAVPlayer: player, motionManager: motionManager)
        
        addChildViewController(swifty360ViewController)
        //view.addSubview(swifty360ViewController.view)
        swifty360ViewController.didMove(toParentViewController: self)
        
        
        swifty360ViewController1 = Swifty360ViewController(withAVPlayer: player, motionManager: motionManager)
        addChildViewController(swifty360ViewController1)
        //view.addSubview(swifty360ViewController1.view)
        swifty360ViewController1.didMove(toParentViewController: self)
        
        
        // Create a stack
        let stackView = UIStackView(arrangedSubviews: [swifty360ViewController1.view,swifty360ViewController.view])
        stackView.axis = .horizontal
        stackView.distribution = .fillEqually
        stackView.alignment = .fill
        stackView.spacing = 0
        stackView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(stackView)
        let stackView_H = NSLayoutConstraint.constraints(
            withVisualFormat: "H:|-0-[stackView]-0-|",  //horizontal constraint 0 points from left and right side
            options: NSLayoutFormatOptions(rawValue: 0),
            metrics: nil,
            views: ["stackView":stackView])
        let stackView_V = NSLayoutConstraint.constraints(
            withVisualFormat: "V:|-0-[stackView]-0-|", //vertical constraint 0 points from top and bottom
            options: NSLayoutFormatOptions(rawValue:0),
            metrics: nil,
            views: ["stackView":stackView])
        view.addConstraints(stackView_H)
        view.addConstraints(stackView_V)

Thanks

**Comment by abdullahselek** [comment]
Hi @konalexiou I didn't try using Swifty360Player on stereoscopic, your solution might work I can only say some basic improvements with your code. You can try using `Swifty360View` instead of `Swifty360ViewController`.
