### ISSUE TITLE
Suggestion: Give access to the UIPanGestureRecognizer handler in Swifty360View

### ISSUE THREAD

**Issue by mikado2005** [abdullahselek/Swifty360Player#20]
Hi, great package!  One easy-to-implement suggestion: In Swifty360View, create some access to the internal function, Swifty360CameraController.handlePan().  Right now, while Swifty360CameraController is an "open class", Swifty360View's cameraController var is private.  Hence it doesn't matter that an app can create and modify a Swifty360CameraController, I don't see any way of then using it.

What I'm currently trying to do is control panning from touches made on a device whilst projecting the Swifty360View onto an AirPlay screen.  I'm blocked from forwarding gestures made on the iOS device to Swifty360View, which only wants to accept gestures directly from its own view.

**Comment by abdullahselek** [comment]
Hi @mikado2005, good point please open a PR with your suggested changes and I'll take a look.

**Comment by abdullahselek** [comment]
Closing this as @mikado2005's PR has already been merged.
