### ISSUE TITLE
Distorted straight lines in video

### ISSUE THREAD

**Issue by KaiKruschel** [abdullahselek/Swifty360Player#3]
When loading a 360° video, horizontal lines that are supposed to be straight are wavy. This seems to apply to all videos I load in the player. In a different 360 video player app they appear straight, so it does not appear to be a problem with the encoding. 

Do you have any ideas what might cause this behavior?

Best,
Kai

**Comment by abdullahselek** [comment]
Hi @KaiKruschel thanks for your message, I'm sorry I don't have any idea and I don't have much time to investigate :(.

**Comment by KaiKruschel** [comment]
Ok, then I'll have to look for an alternative. Thanks anyways.
