### ISSUE TITLE
import Foundation in Swifty360MotionManagerObserverItem

### ISSUE THREAD

**Issue by OrangeInnovationRomaniaDev** [abdullahselek/Swifty360Player#30]
Hello, 

Can you please add "import Foundation" in file named Swifty360MotionManagerObserverItem at the beginning in 0.2.6 version
<img width="919" alt="Screenshot 2023-02-14 at 18 41 07" src="https://user-images.githubusercontent.com/92384965/218801004-c0ac35a9-bdc8-4df2-b8dc-780922aff62b.png">

**Comment by abdullahselek** [comment]
I've just released a new patch version for the fix `0.2.7`, please update your pod.
