### ISSUE TITLE
How to support iOS9 in swift 4.2

### ISSUE THREAD

**Issue by Shannon-Yang** [abdullahselek/Swifty360Player#4]
Since our application needs to support ios9 and above, can we support ios9 on swift4.2？

**Comment by abdullahselek** [comment]
Hi @Shannon-Yang thanks for your interest. I think the best way would be cloning this repository and making some changes on the code base.

**Comment by Shannon-Yang** [comment]
@abdullahselek thank you！ I have made changes in my project
